//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace volleyball {
	
	
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("ICSharpCode.SettingsEditor.SettingsCodeGeneratorTool", "5.1.0.5216")]
	internal sealed partial class app : global::System.Configuration.ApplicationSettingsBase {
		
		private static app defaultInstance = ((app)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new app())));
		
		public static app Default {
			get {
				return defaultInstance;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int AnzFelder {
			get {
				return ((int)(this["AnzFelder"]));
			}
			set {
				this["AnzFelder"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string FTPPw {
			get {
				return ((string)(this["FTPPw"]));
			}
			set {
				this["FTPPw"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string FTPUrl {
			get {
				return ((string)(this["FTPUrl"]));
			}
			set {
				this["FTPUrl"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string FTPUser {
			get {
				return ((string)(this["FTPUser"]));
			}
			set {
				this["FTPUser"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool Kreuzspiele {
			get {
				return ((bool)(this["Kreuzspiele"]));
			}
			set {
				this["Kreuzspiele"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Minsatzkr {
			get {
				return ((int)(this["Minsatzkr"]));
			}
			set {
				this["Minsatzkr"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Minsatzpl {
			get {
				return ((int)(this["Minsatzpl"]));
			}
			set {
				this["Minsatzpl"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Minsatzvr {
			get {
				return ((int)(this["Minsatzvr"]));
			}
			set {
				this["Minsatzvr"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Minsatzzw {
			get {
				return ((int)(this["Minsatzzw"]));
			}
			set {
				this["Minsatzzw"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Pausekrpl {
			get {
				return ((int)(this["Pausekrpl"]));
			}
			set {
				this["Pausekrpl"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Pauseminkr {
			get {
				return ((int)(this["Pauseminkr"]));
			}
			set {
				this["Pauseminkr"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Pauseminvr {
			get {
				return ((int)(this["Pauseminvr"]));
			}
			set {
				this["Pauseminvr"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Pauseminzw {
			get {
				return ((int)(this["Pauseminzw"]));
			}
			set {
				this["Pauseminzw"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Pauseplehrung {
			get {
				return ((int)(this["Pauseplehrung"]));
			}
			set {
				this["Pauseplehrung"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Pausevrzw {
			get {
				return ((int)(this["Pausevrzw"]));
			}
			set {
				this["Pausevrzw"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Pausezwkr {
			get {
				return ((int)(this["Pausezwkr"]));
			}
			set {
				this["Pausezwkr"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string Pdfpath {
			get {
				return ((string)(this["Pdfpath"]));
			}
			set {
				this["Pdfpath"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Satzkr {
			get {
				return ((int)(this["Satzkr"]));
			}
			set {
				this["Satzkr"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Satzpl {
			get {
				return ((int)(this["Satzpl"]));
			}
			set {
				this["Satzpl"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Satzvr {
			get {
				return ((int)(this["Satzvr"]));
			}
			set {
				this["Satzvr"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Satzzw {
			get {
				return ((int)(this["Satzzw"]));
			}
			set {
				this["Satzzw"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("")]
		public string Startturnier {
			get {
				return ((string)(this["Startturnier"]));
			}
			set {
				this["Startturnier"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("False")]
		public bool Vorplatzspiele {
			get {
				return ((bool)(this["Vorplatzspiele"]));
			}
			set {
				this["Vorplatzspiele"] = value;
			}
		}
		
		[global::System.Configuration.UserScopedSettingAttribute()]
		[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
		[global::System.Configuration.DefaultSettingValueAttribute("0")]
		public int Zeitfinale {
			get {
				return ((int)(this["Zeitfinale"]));
			}
			set {
				this["Zeitfinale"] = value;
			}
		}
	}
}
